еуfrolikov_igor_test_homepage:
    path:     /
    defaults: { _controller: еуFrolikovIgorTestBundle:Default:index }

еуfrolikov_igor_test_contacts:
    path:     /helloworld/{name}/
    defaults: { _controller: еуFrolikovIgorTestBundle:Helloworld:index }
